server:
  port: 8100

gateway:
  host: localhost
  port: 18023

swagger:
  enable: true
  title: 决策引擎规则模块接口文档
  description:
  serviceUrl: http://localhost:${server.port}/
  version: 1.0.0
  controllers: com.efy.rule.controller

#打印sql到日志文件
logging:
  config: classpath:config/logback-spring.xml
  level:
    com.sunyard.rule.mapper: DEBUG
    com.sunyard: debug
    root: info
